### ISSUE TITLE
Blizzard_SharedXMLBase/Pools.lua:147: bad argument #1 to 'pairs' (table expected, got nil)

### ISSUE THREAD

**Issue by Thrumbar** [kurapica/EnhanceBattlefieldMinimap#4]
8x Blizzard_SharedXMLBase/Pools.lua:147: bad argument #1 to 'pairs' (table expected, got nil)
[string "@Scorpio/Modules/Core.lua"]:78: in function <Scorpio/Modules/Core.lua:73>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@EnhanceBattlefieldMinimap/EnhanceBattlefieldMinimap.lua"]:681: in function <...anceBattlefieldMinimap/EnhanceBattlefieldMinimap.lua:612>
[string "=(tail call)"]: ?
[string "@Scorpio/PLoop/System/Threading.lua"]:90: in function <Scorpio/PLoop/System/Threading.lua:87>
[string "@Scorpio/PLoop/System/Threading.lua"]:94: in function <Scorpio/PLoop/System/Threading.lua:93>

Locals:
map = <table> {
}
(for state) = <table> {
}
(for control) = <table> {
 MapCanvasDataProviderMixin = <table> {
 }
 _G = <table> {
 }
 __PLOOP_ENV_BSENV = <table> {
 }
}
obj = <table> {
 MapCanvasDataProviderMixin = <table> {
 }
 _G = <table> {
 }
 __PLOOP_ENV_BSENV = <table> {
 }
}
ok = false
err = "Blizzard_SharedXMLBase/Pools.lua:147: bad argument #1 to 'pairs' (table expected, got nil)"

**Comment by kurapica** [comment]
Fixed in v164
